name: List S3 buckets
run-name: List S3 buckets #${{ github.run_number }}

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  listing_buckets:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE || secrets.IAM_ROLE }}
          audience: sts.amazonaws.com
          role-session-name: github-actions-${{ github.run_id }}
          unset-current-credentials: true

      - name: List S3 buckets
        run: |
          echo "Listing S3 Buckets"
          aws s3 ls

