name: List S3 bucketssss

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  listing_buckets:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Debug OIDC token claims
        if: always()
        uses: actions/oidc-debugger@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.IAM_ROLE }}
        
        
       

      - name: List S3 buckets
        run: |
          echo "Listing S3 Buckets"
          aws s3 ls

