name: List S3 buckets

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  listing_buckets:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::123456789100:role/my-github-actions-role
      - name: List S3 buckets
        run: aws s3 ls

